<a href="https://colab.research.google.com/github/Soheillbf/Deep-Learning-in-CFD/blob/main/Session2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
!nvidia-smi

Wed Mar 22 13:14:44 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P0    25W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [6]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [11]:
!pip3 install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [23]:
import torch  
scaler = torch.tensor(2.5)
print(scaler)
Vector1D = torch.tensor([1,2,3,4,5])
print(Vector1D)
Vector2D = torch.tensor([[1],[2],[3],[4]]) 
print(Vector2D)
print(Vector2D.dtype)
##Converting  the data type... 
Vector2D_1 = torch.tensor([[1],[2],[3],[4]], dtype=torch.int32)
print(Vector2D_1)
print(Vector2D_1.dtype)
Tensor3D= torch.tensor([
    [[1,2,3,4],[5,6,7,8]],
    [[1,2,3,4],[5,6,7,8]]
])
print(Tensor3D)

tensor(2.5000)
tensor([1, 2, 3, 4, 5])
tensor([[1],
        [2],
        [3],
        [4]])
torch.int64
tensor([[1],
        [2],
        [3],
        [4]], dtype=torch.int32)
torch.int32
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]])


In [20]:
  scaler.dtype

torch.float32